# Generated by Django 5.0.4 on 2024-04-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
