# Generated by Django 5.0.4 on 2024-04-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_orderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='date',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='date_accepted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='date_requested',
            field=models.DateTimeField(null=True),
        ),
    ]
