# Generated by Django 5.0.4 on 2024-04-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_orderhistory_date_orderhistory_date_accepted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name_plural': 'Order History'},
        ),
    ]
