# Generated by Django 5.0.4 on 2024-05-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_cartitems_options_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
