# Generated by Django 5.0.4 on 2024-05-03 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid

def create_default_cart(apps, schema_editor):
    Cart = apps.get_model('dashboard', 'Cart')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    CartItems = apps.get_model('dashboard', 'CartItems')

    # Create a default cart for existing users
    default_cart = Cart.objects.create(
        user=User.objects.first(),  # Associate with the first user as a default
        unique_id=uuid.uuid4(),
    )

    # Assign all existing CartItems to this default cart
    CartItems.objects.all().update(cart=default_cart)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_cartitems_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
