# Generated by Django 5.0.4 on 2024-05-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_product_price_ordercustomer_ordercustomeritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birthday',
        ),
    ]
