# Generated by Django 5.0.4 on 2024-05-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_remove_customer_birthday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
