# Generated by Django 5.0.4 on 2024-05-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_ordercustomer_contact_ordercustomer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercustomer',
            name='contact',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
