# Generated by Django 5.0.4 on 2024-05-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_ordercustomer_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercustomer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='ordercustomer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ordercustomer',
            name='transaction_id',
        ),
    ]
