# Generated by Django 5.0.4 on 2024-05-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_remove_ordercustomer_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
